name: Package Application with Pyinstaller

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Show current folder
        run: ls
        
      - name: Install dependencies
        run: pip install -r ./requirements.txt
        
      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile --icon=DM.ico main.py

      - name: copying
        run: |
          cp -a ./settings ./dest
          cp -a ./textures ./dest
        

      - uses: actions/upload-artifact@v4
        with:
          name: downloader
          path: dist/*
